
<?php echo $message ?>
<form method="post" action="<?php echo App::config('url') ?>admin/changeUserInfo/<?php echo Session::getInstance()->getUser()->id ?>">

    <div class="form-group">

        <label for="firstname">New First name</label>
        <input type="firstname" name="firstname">

        <label for="lastname">New Last name</label>
        <input type="lastname" name="lastname">

        <label for="email">New Email</label>
        <input type="email" name="email">

        <label for="password">New Password</label>
        <input type="password" name="pass">

        <label for="password">Confirm New Password</label>
        <input type="password" name="confirmpass">

    </div>

    <button type="submit" class="button-primary">Change</button>

</form>