

 <?php if(!Session::getInstance()->isLoggedIn()): ?>    
    <a href="<?php echo App::config("url")."admin/login" ?>">Login</a>
    <a href="<?php echo App::config("url")."admin/registration" ?>">Registration</a>
<?php else: ?>
 <img style="max-width: 100px" src="<?= '../../images/'.Session::getInstance()->getUser()->image;?>">
    <a href="<?php echo App::config("url")."admin/logout" ?>">Logout <?php echo Session::getInstance()->getUser()->firstname ?></a>
     <a href="<?php echo App::config("url")."admin/change" ?>">Change Info</a>
<?php endif; ?>
<div class="container"><h1>SOCIAL NETWORK</h1></div>

<?php if(Session::getInstance()->isLoggedIn()):?>
<form method="post" action="<?php echo App::config('url') ?>Index/newPost">

    <div class="container">

        <label for="content">What's on your mind?</label>
        <input class="u-full-width" id="content" name="content"><br/>
        Tags:
        <input id="tag" name="tag"><br/>
        <button type="submit" class="button-primary">Save</button>
    </div>



</form>
<?php endif; ?>

<div class="container">



 <?php foreach ($posts as $post): ?>
    <p>
        <cite><?= htmlspecialchars($post->getUser()) ?><br/></cite>

        <a style="text-decoration: none" href="<?php echo App::config('url') ?>Index/view/<?= $post->getId() ?> ">
            <?= htmlspecialchars($post->getContent()) ?> </a> <br />
            <?php echo $post->date ?><br/>
            <?php if( Session::getInstance()->isLoggedIn() ): ?>
            <a href="<?php echo App::config('url') ?>admin/like/<?php echo $post->id ?>">Like</a>
                <a href="<?php echo App::config('url') ?>admin/dislikePost/<?php echo $post->id ?>">Dislike</a><br/>
            <?php endif; ?>

            Likes (<?php echo $post->getLikes() ?>)
        Dislikes (<?php echo $post->getDislikes() ?>)

        Comments (<?= count($post->getComments()) ?>)


    </p>
<?php endforeach; ?>
</div>

<?php //echo password_hash("t", PASSWORD_DEFAULT);


?>