<a href="<?php echo App::config("url") ?>">Index</a><hr />
<div class="container">
<?php if( Session::getInstance()->isLoggedIn() &&
    $post->getUserid()==Session::getInstance()->getUser()->id): ?>
<a href="<?php echo App::config("url") ?>admin/delete/<?php echo $post->getId() ?>">Delete post</a><br />
<?php endif; ?>

<cite><?= htmlspecialchars($post->getUser()) ?></cite>
<h2><?= htmlspecialchars($post->getContent()) ?></h2>
    <?php echo $post->date ?>
    Likes: <?php echo $post->getLikes() ?>


<h4>Comments:</h4>
<?php foreach ($post->getComments() as $comment): ?>
    <p>
        <cite><?= htmlspecialchars($comment->user) ?></cite>

       <?php echo $comment->content ?><br />
        <?php echo $comment->date ?>
    </p>
<?php endforeach; ?>

<?php if( Session::getInstance()->isLoggedIn() ): ?>

<form method="post" action="<?php echo App::config('url') ?>admin/comment/<?php echo $post->getId() ?>">

<div class="form-group">
        <label for="content">New comment</label>
        <input id="content" name="content">
    </div>

    <button type="submit" class="btn btn-primary">Save</button>

</form>
<?php endif; ?>
</div>
