<div id="fb-root"></div>
<script>(function(d, s, id) {
        let js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.2';
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>


<a href="<?php echo App::config("url") ?>">Index</a><hr />
<div class="container">
<?php if( Session::getInstance()->isLoggedIn() &&
    ($post->getUserid()==Session::getInstance()->getUser()->id) || Session::getInstance()->getUser()->role==='admin'): ?>
<a href="<?php echo App::config("url") ?>admin/delete/<?php echo $post->getId() ?>">Delete post</a><br />
<?php endif; ?>

<cite><?= htmlspecialchars($post->getUser()) ?></cite>
<h2><?= htmlspecialchars($post->getContent()) ?></h2>
    <?php echo $post->date ?><br/>
    Tags:
    <div class="row">
    <?php foreach ($post->getTags() as $tag): ?>

        <div class="one column">
        <?php echo $tag ?>
        </div>

    <?php endforeach; ?>
    </div>
    Likes: <?php echo $post->getLikes() ?><br/>
    Dislikes: <?= $post->getDislikes() ?><br/>
    <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script><br/>
    <div style="vertical-align: top;" class="fb-share-button" data-href="<?= App::config('url'). 'Index/view/'.$post->getId()?>" data-layout="button" data-size="small" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>


<h4>Comments:</h4>
<?php foreach ($post->getComments() as $comment): ?>
    <p>
        <cite><?= htmlspecialchars($comment->user) ?></cite>

       <?php echo $comment->content ?><br />
        <?php echo $comment->date ?>
        <?php if(Session::getInstance()->isLoggedIn() && Session::getInstance()->getUser()->role==='admin'): ?>
        <a href="<?php echo App::config('url') ?>admin/deleteComment/<?php echo $comment->id ?>">Delete Comment</a><br/>
        <?php endif; ?>
        <a href="<?php echo App::config('url') ?>admin/dislikeComment/<?php echo $comment->id ?>">Dislike</a><br/>

        Dislikes: <?= $comment->dislikes ?><br/>
    </p>
<?php endforeach; ?>

<?php if( Session::getInstance()->isLoggedIn() ): ?>

<form method="post" action="<?php echo App::config('url') ?>admin/comment/<?php echo $post->getId() ?>">

<div class="form-group">
        <label for="content">New comment</label>
        <input id="content" name="content">
    </div>

    <button type="submit" class="btn btn-primary">Save</button>

</form>
<?php endif; ?>
</div>
